### ISSUE TITLE
Is this Centralized?

### ISSUE THREAD

**Issue by yuvi76** [tokend/developer-edition#14]
I'm testing this but I can't understand how can I connect my node to the server?
For each type we have to request to admin to approve (asset, polls). **So is this Centralized**?
Master Admin can all answer polls. I think poll created by the corporate user so it should between general user and corporate user but in this admin also can see the voted answer, is this fair?

**Comment by Volendi** [comment]
It is a demonstration deploy with one node. It contains not only one node, but also other services that allow running the whole system. For details read [docs](https://docs.tokend.io/). If you want to connect it to an already running environment, you should manually configure the node to access this environment.

> For each type we have to request to admin to approve (asset, polls)

It is configurable, so you can configure the system to don't ask for an admin review for some actions. To understand how it works check this [guide](https://docs.tokend.io/#tag/Guides/paths/~1reviewable_request/get) 

> I think poll created by the corporate user so it should between general user and corporate user but in this admin also can see the voted answer, is this fair?

Admin in your case means the system owner. The system owner can access all data stored in the blockchain. In a real system, you may restrict admins to access some data.
